spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zooShop
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password: 123
    baseline-description: "init"
    baseline-version: 0


server:
  error:
    include-message: always
