spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zooShop
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password: 123
    baseline-description: "init"
    baseline-version: 0
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB


server:
  error:
    include-message: always

local:
  server:
    host: 127.0.0.1
    port: 8080
  upload:
    image: /media/images/
logging:
  file:
    name: application.log
  level:
    ru.sfu.zooshopback: DEBUG