CREATE SEQUENCE IF NOT EXISTS comment_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE comments
(
    id         BIGINT       NOT NULL,
    product_id BIGINT       NOT NULL,
    content    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE;